// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrPpaieL1GROXc0N_IOnC10BUpZU6ZPt0',
    appId: '1:1011731760901:web:03d5a92fe964b4e3a4d96c',
    messagingSenderId: '1011731760901',
    projectId: 'thenotes-project-2',
    authDomain: 'thenotes-project-2.firebaseapp.com',
    storageBucket: 'thenotes-project-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoWl3_3L-ykQrOBBRg3Jt-tgl5BX9rFKg',
    appId: '1:1011731760901:android:e251fa5821aea071a4d96c',
    messagingSenderId: '1011731760901',
    projectId: 'thenotes-project-2',
    storageBucket: 'thenotes-project-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxZpnrqc1S2JpYTvN9DAvbrfOI-aBXuxE',
    appId: '1:1011731760901:ios:234b5502817e4b6ca4d96c',
    messagingSenderId: '1011731760901',
    projectId: 'thenotes-project-2',
    storageBucket: 'thenotes-project-2.appspot.com',
    iosClientId: '1011731760901-p4dhcl2rppeier49ufnmge85sdtp13sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.thenotes',
  );
}
